version: '2'

services:
  web:
    build: .
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=developer
      - MYSQL_USER=developer
      - MYSQL_DATABASE=onmedia
    ports:
      - 3306:3306
    volumes:
      - ./db/backups:/backups
      - ./db/data:/var/lib/mysql
