version: '2'

services:
  web:
    build: .
    ports:
      - 8080:80
      - 443:443
    volumes:
        - ./:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=developer
      - MYSQL_USER=developer
      - MYSQL_DATABASE=onmedia
    ports:
      - 3306:3306
    volumes:
      - ./db/backups:/backups
      - ./db/data:/var/lib/mysql
